services:
  redis-master:
    image: redis:latest
    container_name: redis
    command:
      - redis-server
    volumes:
      - './docker_info/redis_data:/data'
    ports:
      - "6379:6379"
    restart: on-failure

  nats:
    image: nats:latest
    container_name: nats
    entrypoint: /nats-server
    command: "-c /config/server.conf"
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - "./docker_info/nats/data:/data"
      - "./docker_info/nats/config/server.conf:/config/server.conf"

  nats-nui:
    image: ghcr.io/nats-nui/nui:latest
    container_name: nats-nui
    ports:
      -  "31311:31311"
    volumes:
      - "./docker_info/nui/db:/db"
    depends_on:
      - nats
